require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/configuration_items", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ConfigurationItem. As you add validations to ConfigurationItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  let(:admin_user) { FactoryBot.create(:admin_user) }
  let(:user) { FactoryBot.create(:user) }
  let(:ci) { FactoryBot.create(:configuration_item) }

  describe "GET /index" do
    it "renders a successful response" do
      ConfigurationItem.create! valid_attributes
      get configuration_items_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      configuration_item = ConfigurationItem.create! valid_attributes
      get configuration_item_url(configuration_item)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      sign_in admin_user

      get new_configuration_item_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      configuration_item = ConfigurationItem.create! valid_attributes
      get edit_configuration_item_url(configuration_item)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ConfigurationItem" do
        expect {
          post configuration_items_url, params: { configuration_item: valid_attributes }
        }.to change(ConfigurationItem, :count).by(1)
      end

      it "redirects to the created configuration_item" do
        post configuration_items_url, params: { configuration_item: valid_attributes }
        expect(response).to redirect_to(configuration_item_url(ConfigurationItem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ConfigurationItem" do
        expect {
          post configuration_items_url, params: { configuration_item: invalid_attributes }
        }.to change(ConfigurationItem, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post configuration_items_url, params: { configuration_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested configuration_item" do
        configuration_item = ConfigurationItem.create! valid_attributes
        patch configuration_item_url(configuration_item), params: { configuration_item: new_attributes }
        configuration_item.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the configuration_item" do
        configuration_item = ConfigurationItem.create! valid_attributes
        patch configuration_item_url(configuration_item), params: { configuration_item: new_attributes }
        configuration_item.reload
        expect(response).to redirect_to(configuration_item_url(configuration_item))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        configuration_item = ConfigurationItem.create! valid_attributes
        patch configuration_item_url(configuration_item), params: { configuration_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested configuration_item" do
      configuration_item = ConfigurationItem.create! valid_attributes
      expect {
        delete configuration_item_url(configuration_item)
      }.to change(ConfigurationItem, :count).by(-1)
    end

    it "redirects to the configuration_items list" do
      configuration_item = ConfigurationItem.create! valid_attributes
      delete configuration_item_url(configuration_item)
      expect(response).to redirect_to(configuration_items_url)
    end
  end
end
